# Generated by Django 4.0.5 on 2022-06-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('bio', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, default='', upload_to='profile/')),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
