# Generated by Django 4.0.5 on 2022-06-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=30)),
                ('link', models.URLField()),
                ('description', models.TextField(max_length=300)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
