# Generated by Django 4.0.5 on 2022-06-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='content_avr',
            new_name='content_average',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='design_avr',
            new_name='design_average',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='usability_avr',
            new_name='usability_average',
        ),
    ]
