# Generated by Django 4.0.5 on 2022-06-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_rename_content_avr_ratings_content_average_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='my image', upload_to='home/'),
        ),
    ]
