# Generated by Django 4.0.5 on 2022-06-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_remove_profile_profile_pic_remove_profile_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='my image', upload_to='profile/'),
        ),
    ]
