# Generated by Django 4.0.5 on 2022-06-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_alter_profile_image_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
