# Generated by Django 4.0.5 on 2022-06-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_profile_image_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='no image', upload_to='profile/'),
        ),
    ]
